name: build-and-deploy

on:
  push:
    paths: 
      - '**'
      - '!.github/**' 
      - '!README.md'
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: main
      env:
        ACCESS_TOKEN:  ${{ secrests.ACCESS_TOKEN }}
      run: |
        sudo snap install hugo --channel=extended
        git config --global user.email "h.nakamura0903@gmail.com"
        git config --global user.name "nekoTheShadow"
        git clone --recursive -b master https://github.com/nekoTheShadow/nekoTheShadow.github.io.admin.git ${GITHUB_WORKSPACE}/nekoTheShadow.github.io.admin
        git clone --recursive -b master https://github.com/nekoTheShadow/nekoTheShadow.github.io.git       ${GITHUB_WORKSPACE}/nekoTheShadow.github.io.admin/public
        cd ${GITHUB_WORKSPACE}/nekoTheShadow.github.io.admin
        hugo
        cd ${GITHUB_WORKSPACE}/nekoTheShadow.github.io.admin
        msg=$(git log -1 --pretty="%s (from github actions)")
        cd ${GITHUB_WORKSPACE}/nekoTheShadow.github.io.admin/public
        git add -A
        git commit -m "$msg"
        git push https://x-access-token:${ACCESS_TOKEN}@github.com/nekoTheShadow/nekoTheShadow.github.io.git master
